-- Predictions are read-only. Explicit Undo uses the native run-loading lifecycle.
local mod = SMODS and SMODS.current_mod
if not mod then return end -- Steamodded reports missing dependencies before load.
if rawget(_G, 'ORACLE') then return end
local O = {version = '0.16.3', phase = 11, mod = mod}
ORACLE = O
local function load_module(path)
    local chunk, err = SMODS.load_file(path, mod.id)
    if not chunk then error(err or ('Oracle: cannot load '..path)) end
    return chunk()
end
O.configuration=load_module('configuration.lua')
O.config=O.configuration.normalize(mod.config)
mod.config=O.config
O.compatibility = load_module('compatibility.lua')
O.state_reader = load_module('state_reader.lua')
O.data = load_module('simulation/data.lua')
O.backend = load_module('simulation/backend.lua')
O.rng = load_module('rng.lua')(O.data, O.backend)
O.snapshot = load_module('simulation/snapshot.lua')(O.data)
O.ante_prediction = load_module('prediction/ante.lua')(O.data, O.rng)
O.shop_snapshot = load_module('simulation/shop_snapshot.lua')(O)
O.shop_prediction = load_module('prediction/shop.lua')(O)
O.pack_prediction = load_module('prediction/packs.lua')(O)
O.deck_prediction = load_module('prediction/deck.lua')(O)
O.validator = load_module('debug/validator.lua')(O)
O.diagnostics = load_module('debug/diagnostics.lua')(O)
O.controller = load_module('controller.lua')(O)
O.tag_rewards = load_module('prediction/tag_rewards.lua')(O)
O.tag_prediction = load_module('prediction/tags.lua')(O)
O.tag_pipeline = load_module('prediction/tag_pipeline.lua')(O)
O.consumables = load_module('prediction/consumables.lua')(O)
O.deck_state = load_module('prediction/deck_state.lua')(O)
O.jokers = load_module('prediction/jokers.lua')(O)
O.events = load_module('prediction/events.lua')(O)
O.bosses = load_module('prediction/bosses.lua')(O)
O.hook = load_module('prediction/hook.lua')(O)
O.engine = load_module('prediction/engine.lua')(O)
O.text = load_module('localization.lua')(load_module('localization/en-us.lua'))
O.ui = load_module('ui/components.lua')(O)
O.tag_ui = load_module('ui/tags.lua')(O)
O.tag_ui.install()
O.overview = load_module('ui/overview.lua')(O)
O.settings = load_module('ui/settings.lua')(O)
O.events_ui = load_module('ui/events.lua')(O)
O.events_ui.install()
O.main = load_module('ui/main.lua')(O)
O.main.install()
O.main.register('tags','oracle_chain_tab',O.tag_ui.definition)
O.ante_ui = load_module('ui/ante.lua')(O)
O.main.register('ante', 'oracle_ante_tab', O.ante_ui.definition)
O.ante_ui.install()
O.preview_card = load_module('ui/preview_card.lua')(O)
O.tooltip = load_module('ui/tooltip.lua')(O)
O.shortcut = load_module('ui/shortcut.lua')(O)
O.shortcut.install()
O.shop_ui = load_module('ui/shop.lua')(O)
O.boss_ui = load_module('ui/boss.lua')(O)
O.main.register('shop', 'oracle_shop_tab', O.shop_ui.definition)
O.main.register('boss', 'oracle_boss_tab', O.boss_ui.definition)
O.shop_ui.install()
O.boss_ui.install()
O.packs_ui=load_module('ui/packs.lua')(O)
O.main.register('packs','oracle_packs_tab',O.packs_ui.definition)
O.packs_ui.install()
O.deck_ui=load_module('ui/deck.lua')(O)
O.main.register('deck','oracle_deck_tab',O.deck_ui.definition)
O.deck_ui.install()
O.rng_ui=load_module('ui/rng.lua')(O)
O.main.register('rng','oracle_rng_tab',O.rng_ui.definition)
O.consumables_ui=load_module('ui/consumables.lua')(O)
O.deck_after_ui=load_module('ui/deck_after.lua')(O)
O.deck_after_ui.install()
O.main.register('consumables','oracle_consumables_tab',O.consumables_ui.definition)
O.consumables_ui.install()
O.jokers_ui=load_module('ui/jokers.lua')(O)
O.main.register('jokers','oracle_jokers_tab',O.jokers_ui.definition)
O.jokers_ui.install()
O.boss_analysis_ui=load_module('ui/boss_analysis.lua')(O)
O.main.register('boss_analysis','oracle_boss_analysis_tab',O.boss_analysis_ui.definition)
O.boss_analysis_ui.install()
O.controller.install()
O.pack_validator=load_module('debug/pack_validator.lua')(O)
O.pack_validator.install()
O.deck_validator=load_module('debug/deck_validator.lua')(O)
O.deck_validator.install()
O.tag_validator=load_module('debug/tag_validator.lua')(O)
O.tag_validator.install()
O.tag_chain_validator=load_module('debug/tag_chain_validator.lua')(O)
O.tag_chain_validator.install()
O.consumable_validator=load_module('debug/consumable_validator.lua')(O)
O.consumable_validator.install()
O.tag_reward_validator=load_module('debug/tag_reward_validator.lua')(O)
O.tag_reward_validator.install()
O.joker_validator=load_module('debug/joker_validator.lua')(O)
O.joker_validator.install()
O.boss_validator=load_module('debug/boss_validator.lua')(O)
O.boss_validator.install()
O.hook_controller=load_module('hook_controller.lua')(O)
O.hook_controller.install()
O.card_insight=load_module('ui/card_insight.lua')(O)
O.card_insight.install()
O.quick=load_module('prediction/quick.lua')(O)
O.quick_ui=load_module('ui/quick_preview.lua')(O)
O.quick_ui.install()
O.undo_storage=load_module('undo/storage.lua')()
O.undo_history=load_module('undo/history.lua')(O,O.undo_storage)
O.undo=load_module('undo/runtime.lua')(O,O.undo_history)
O.undo.install()
O.undo_ui=load_module('ui/undo.lua')(O)
O.undo_ui.install()
O.main.register('undo','oracle_undo_tab',O.undo_ui.definition)
O.diagnostics_ui=load_module('ui/diagnostics.lua')(O)
O.diagnostics_ui.install()
mod.config_tab = O.settings.definition
if sendInfoMessage then
    sendInfoMessage('Oracle 0.16.3: Blind forecasts use the live native candidate order without advancing RNG.', 'Oracle')
end
