return {misc = {dictionary = {
    oracle_undo_tab='Undo', oracle_undo_button='Undo last action', oracle_undo_round='Round',
    oracle_undo_scope='Restores this run; unlocks and career stats are kept.',
    oracle_undo_pack_hint='A Booster is undone as a whole, back to before opening.',
    oracle_undo_hotkey='F9: undo, including from the game-over screen.',
    oracle_undo_count='Available checkpoints:',
    oracle_undo_empty='No earlier checkpoint recorded for this run.',
    oracle_undo_wait='Wait for the current animation or load to finish.',
    oracle_undo_unavailable='Undo is unavailable in this state or version.',
    oracle_undo_error='Undo error. History files are retained; check the log.',
    oracle_undo_write='Cannot write Undo history. The native save is preserved.',
    oracle_undo_corrupt='Invalid checkpoint. Nothing has been restored.',
    oracle_undo_profile='Undo history belongs to another profile.',
    oracle_undo_experimental='Experimental · current-run checkpoints, starting after installation.',
    oracle_event_depth='Probability event depth',
    oracle_event_condition='Experimental: repeated eligible checks at the current Ante.',
    oracle_event_wheel_condition='Experimental: another Wheel each time; successful editions persist.',
    oracle_event_other_actions='No intervening actions, shared-stream rolls or acquisition simulated.',
    oracle_event_no_target='Stopped: no editionless Joker remains.',
    oracle_event_destroy_boundary='Stopped at the destruction check; this source cannot safely continue.',
    oracle_quick_conditional='Experimental · if used/opened now',
    oracle_quick_more='More in Oracle:',
    oracle_quick_stack='Current stack; before the next shuffle.',
    oracle_quick_shop_use='Current state; purchase effects excluded.',
    oracle_jokers_tab='Joker Triggers',
    oracle_joker_empty='No supported random-effect Joker / Lucky / Glass card owned.',
    oracle_joker_nonrandom='Lucky Cat and Hit the Road have no independent random roll.',
    oracle_joker_conditional='Experimental - next qualified trigger, frozen current state',
    oracle_joker_order_hint='Earlier rolls, retriggers and copied effects can change this result.',
    oracle_joker_current_target='Current target',
    oracle_export_logs='Export logs (F10)',
    oracle_export_hint='Press F10 to export diagnostics',
    oracle_export_success='Diagnostic report exported',
    oracle_export_share='Send this file to the developer for diagnosis.',
    oracle_report_folder='Open report folder',
    oracle_export_failed='Diagnostic export failed',
    oracle_export_failed_hint='Check write access to the game save directory.',
    oracle_pack_custom_soul='Custom Soul generation is not supported.',
    oracle_joker_next_target='Next target',
    oracle_joker_no_room='No available space; this creation does not trigger.',
    oracle_joker_no_target='No eligible target; no random selection.',
    oracle_joker_not_ready='Sale duplication is not ready / no room.',
    oracle_joker_debuffed='This card is currently debuffed.',
    oracle_joker_mult='Mult', oracle_joker_money='Money', oracle_joker_destroy='Destroyed',
    oracle_reset_ante='Reset at Ante',
    oracle_trigger_j_space='Next before-scoring check for a played hand.',
    oracle_trigger_j_gros_michel='Next round-end extinction check.',
    oracle_trigger_j_cavendish='Next round-end extinction check.',
    oracle_trigger_j_bloodstone='Next scoring Heart check.',
    oracle_trigger_j_business='Next scoring face-card check.',
    oracle_trigger_j_reserved_parking='Next held face-card check (not debuffed).',
    oracle_trigger_j_8_ball='Next scoring 8 check with consumable space.',
    oracle_trigger_j_hallucination='Next pack-open check with consumable space.',
    oracle_trigger_m_glass='Next destruction check after scoring this card.',
    oracle_trigger_m_lucky='Next scored activation; Mult and Money can both succeed.',
    oracle_trigger_j_idol='Next target reset, assuming deck remains as shown.',
    oracle_trigger_j_mail='Next rank reset, assuming deck remains as shown.',
    oracle_trigger_j_ancient='Next suit reset; current suit is excluded.',
    oracle_trigger_j_castle='Next suit reset, sampled from the actual deck.',
    oracle_trigger_j_misprint='Next main scoring evaluation.',
    oracle_trigger_j_todo_list='Next round end; visible hands except current target.',
    oracle_trigger_j_invisible='Sell this ready Joker now; Negative is not copied.',
    oracle_trigger_j_perkeo='Next shop exit with current consumable inventory.',
    oracle_trigger_j_madness='Next non-Boss Blind selection with current Jokers.',
    oracle_trigger_j_riff_raff='Next Blind selection; up to two Common Jokers.',
    oracle_trigger_j_cartomancer='Next Blind selection with consumable space.',
    oracle_trigger_j_sixth_sense='First hand is a single 6, with consumable space.',
    oracle_trigger_j_vagabond='Next scoring check that meets its money threshold.',
    oracle_trigger_j_superposition='Next qualifying Straight containing an Ace.',
    oracle_trigger_j_seance='Next qualifying Straight Flush with consumable space.',
    oracle_trigger_j_marble='Next Blind selection; Stone card base shown on hover.',
    oracle_trigger_j_certificate='Next first hand drawn; playing card and seal.',
    oracle_tag_after_pack='Resolve the first pack, then refresh for your choices.',
    oracle_tag_no_room='No Joker space: no Joker generated.',
    oracle_tag_pack_cover='Random cover variant; contents are unchanged.',
    oracle_consumables_tab="Consumables",
    oracle_consume_empty="No consumable in inventory or open pack.",
    oracle_consume_selection="Select valid cards / leave enough space first.",
    oracle_consume_wait="Wait for the current action to finish.",
    oracle_action_unsupported="Unable to predict this action reliably.",
    oracle_consume_direct="Experimental - direct use effects",
    oracle_created="CREATED",
    oracle_destroyed="DESTROYED",
    oracle_target="TARGET",
    oracle_after_use="AFTER USE",
    oracle_success="Success",
    oracle_fail="Fail",
    oracle_money_change="Money change",
    oracle_hand_size_change="Hand size change",
    oracle_consume_selection_hint="Uses current selection. Joker stat/scoring chains are separate.",

    oracle_auto_refresh='Auto Refresh',oracle_show_draw_order='Show Draw Order',
    oracle_show_future_shops='Show Future Shops',oracle_show_packs='Show Packs',oracle_show_voucher='Show Voucher',
    oracle_manual_refresh_hint='Auto Refresh OFF: use Refresh or switch pages to read current state.',
    oracle_feature_hidden='This view is disabled in Oracle Settings.',oracle_slot='Position:',
    oracle_rng_enable='Enable Advanced Info in Settings to inspect RNG state.',
    oracle_rng_readonly='Current per-key RNG state · read only',
    oracle_predicted='Predicted:', oracle_card_key='Card key:',
    oracle_pack_wait='Open this page in a shop or while a pack is open.',
    oracle_pack_unsupported='Pack prediction unavailable for this state or custom rules.',
    oracle_pack_tag_unsupported='Pack prediction unavailable: an unaudited or custom Tag is held.',
    oracle_pack_branch='Each pack is predicted as the FIRST pack opened from this state.',
    oracle_soul_branch='Soul: use immediately after generation, with no other actions.',
    oracle_title = 'Oracle', oracle_overview = 'Overview', oracle_settings = 'Settings',
    oracle_tag_unavailable='Unable to predict reliably',
    oracle_tag_custom='Current custom rules need an isolated adapter.',
    oracle_tag_unsupported='This tag is not supported yet.',
    oracle_tag_queue='This tag combination needs an adapter.',
    oracle_chain_tab='Tag Chain', oracle_stored_doubles='Stored Double Tags',
    oracle_double_pending='Stored for the next non-Double Tag; does not copy itself.',
    oracle_normal_voucher='Normal Voucher', oracle_chain_more='Full results: Oracle → Tag Chain.',
    oracle_chain_reroll='Reroll', oracle_chain_immediate='Immediate after skip',
    oracle_chain_deferred='Resolves in shop (conditional branch)',
    oracle_chain_no_purchase='Rerolls assume no purchases or card use; refresh after actions.',
    oracle_tag_not_generated='The actual blind tag state is not generated yet.',
    oracle_tag_future='Read actual state upon reaching this Ante.',
    oracle_tag_nope='All rare Jokers owned; this tag creates no card.',
    oracle_tag_pending='No eligible initial item; tag remains pending.',
    oracle_tag_experimental='Prediction: Experimental',
    oracle_tag_first_shop='First shop after skipping',
    oracle_tag_condition_1='Assumes pools, owned cards and relevant',
    oracle_tag_condition_2='RNG streams stay unchanged until the shop.',
    oracle_boss_tab = 'Boss Rerolls', oracle_boss_branch = 'Consecutive rerolls at the current Ante.',
    oracle_boss_permission = 'Forecast only; voucher, money and timing requirements still apply.',
    oracle_reroll = 'REROLL', oracle_current_shop = 'CURRENT SHOP', oracle_next_shop = 'NEXT SHOP',
    oracle_boosters = 'BOOSTER PACKS', oracle_shop_branch = 'Assumes no purchases or other actions between rerolls.',
    oracle_shop_wait = 'Next shop preview is available after scoring, on the cash-out screen.',
    oracle_shop_unsupported = 'Shop prediction unavailable: unsupported rules, tags or transition.',
    oracle_cover_unknown = 'Buffoon type confirmed; cover variant is unknown.',
    oracle_type_Joker = 'Joker', oracle_type_Tarot = 'Tarot', oracle_type_Planet = 'Planet',
    oracle_type_Spectral = 'Spectral', oracle_type_Default = 'Playing Card', oracle_type_Enhanced = 'Enhanced Card',
    oracle_type_Booster = 'Booster Pack', oracle_eternal = 'Eternal', oracle_perishable = 'Perishable',
    oracle_rental = 'Rental', oracle_e_foil = 'Foil', oracle_e_holo = 'Holographic',
    oracle_e_polychrome = 'Polychrome', oracle_e_negative = 'Negative',
    oracle_seed = 'SEED', oracle_ante = 'ANTE',
    oracle_current_blind = 'CURRENT BLIND', oracle_upcoming_blind = 'UPCOMING BLIND',
    oracle_completed_blind = 'COMPLETED BLIND',
    oracle_stake = 'STAKE', oracle_deck = 'DECK', oracle_unknown = 'Not available',
    oracle_no_run = 'Start or continue a run to use Oracle.',
    oracle_run_loading = 'Run information is not ready yet.',
    oracle_readonly = 'Current run information',
    oracle_phase1 = 'Future predictions are not available in this build.',
    oracle_refresh = 'Refresh', oracle_enabled = 'Oracle Enabled',
    oracle_advanced = 'Advanced Info',
    oracle_disabled = 'Oracle is disabled. Enable it in Settings.',
    oracle_unverified_version = 'Untested version: only current run information is available.',
    oracle_dependency_missing = 'Oracle requires Steamodded and Lovely.',
    oracle_ui_unavailable = 'Oracle could not open this page.',
    oracle_config_error = 'Settings could not be saved.',
    oracle_version = 'Version',
    oracle_phase2 = 'Boss, Tag and Voucher forecasts are on the Ante tab.',
    oracle_experimental = 'Experimental - conditional prediction',
    oracle_observed = 'Already generated - current run',
    oracle_branch_1 = 'Assumes no purchases, skips or Boss rerolls;',
    oracle_branch_2 = 'owned cards and pools remain unchanged.',
    oracle_small_tag = 'SMALL BLIND TAG', oracle_big_tag = 'BIG BLIND TAG',
    oracle_boss = 'BOSS BLIND', oracle_voucher = 'VOUCHER',
    oracle_validate = 'Validate Predictions', oracle_depth = 'Prediction Depth',
    oracle_prediction_unavailable = 'Prediction unavailable. Check version or mismatch log.',
    oracle_transition = 'Ante transition in progress. Reopen after cashing out.',
    oracle_pool_unsupported = 'Custom pool rules are not supported in this build.',
    oracle_rng_unsupported = 'Requires Windows Balatro with LuaJIT 2.0.5.',
    oracle_resample_limit = 'Resampling limit reached; no result is shown.',
    oracle_consume_effects='Use result',oracle_branch_deck='Deck after use',oracle_before_use='Before use',
    oracle_branch_experimental='Experimental - one use, current selection',
    oracle_branch_boundary='Current stack only; no play, discard or next-Blind shuffle.',
    oracle_branch_pack_boundary='Before pack closes; returning the hand is the next boundary.',
    oracle_deck_branch_unavailable='Cannot reliably build this shadow deck.',
    oracle_deck_branch_draw_boundary='Automatic draws from increased hand size are not simulated yet.',
    oracle_draw_disabled='Enable Show Draw Order in Oracle settings.',
    oracle_deck_tab = 'Deck', oracle_shop_tab = 'Shop', oracle_packs_tab = 'Packs',
    oracle_next_cards='NEXT CARDS - current deck order',
    oracle_pile_next='Next',oracle_pile_hand='Hand',oracle_pile_discard='Discard',oracle_pile_all='All cards',
    oracle_cards_view='Cards',oracle_list_view='List',oracle_empty_pile='This pile is empty.',
    oracle_deck_unavailable='No readable deck in the current run.',
    oracle_deck_boundary='Order updates after draws, card changes and shuffles.',
    oracle_deck_reshuffle='Current stack only; the next Blind will shuffle it.',
    oracle_shop_slots='SHOP SLOTS',
    oracle_shop_sync='Purchases and vouchers update the next forecast automatically.',
    oracle_ante_tab = 'Ante', oracle_rng_tab = 'RNG',
    oracle_face_down_identity='Oracle · Actual face-down card',
    oracle_hook_target='The Hook: discarded if selected cards are played',
    oracle_hook_unavailable='Cannot reliably predict The Hook in this state.',
    oracle_boss_analysis_tab='Boss Effects', oracle_boss_rules='Rules', oracle_boss_cards='Affected Cards', oracle_boss_hand='Hand Plan',
    oracle_boss_current='Experimental · Active Boss · Current state',
    oracle_boss_scheduled='Experimental · This Ante Boss · State held constant',
    oracle_boss_analysis_unsupported='Boss analysis unavailable for this state.', oracle_boss_no_active='No active Boss.',
    oracle_boss_chicot='Boss ability disabled by Chicot.', oracle_boss_disabled='Boss ability is disabled.',
    oracle_boss_hand_size_delta='On entry: hand size', oracle_boss_discards_delta='On entry: discards', oracle_boss_hands_delta='On entry: hands',
    oracle_boss_random_boundary='Rule only: random targets are not simulated here.',
    oracle_boss_draw_boundary='Rule only: draw and face-down events are not simulated.',
    oracle_boss_affected='Boss-debuffed playing cards', oracle_boss_no_debuff='No playing-card debuffs for this snapshot.',
    oracle_boss_card_boundary='Full deck, current traits; other Boss effects remain.',
    oracle_boss_plan_hint='If this hand type is played with this many cards:',
    oracle_boss_blocked='Hand blocked by this Boss', oracle_boss_allowed='No hand-type or size block from this Boss',
    oracle_boss_money='Direct Boss money change', oracle_boss_base='Base chips × Mult',
    oracle_boss_score_boundary='Boss effect only; excludes Jokers and final hand score.',
}}}
