return {descriptions = {Mod = {Oracle = {
    name = 'Oracle / 预知',
    text = {
        '预测商店、补充包、标签与抽牌结果',
        '支持随机事件悬浮预览与当前牌局撤销',
        '{C:attention}F8{}：打开预知　{C:attention}F9{}：撤销',
        '预测不改变 RNG；撤销保留全局进度',
    },
}}}, misc = {dictionary = {
    oracle_undo_tab='撤销', oracle_undo_button='撤销上一次操作', oracle_undo_round='回合',
    oracle_undo_scope='恢复当前牌局；保留全局解锁、成就与生涯统计。',
    oracle_undo_pack_hint='补充包整体撤销，回到开包前，不回退包内单张选牌。',
    oracle_undo_hotkey='F9：直接撤销，失败画面中也可使用。',
    oracle_undo_count='可用历史节点：',
    oracle_undo_empty='当前牌局尚无可撤销的历史节点。',
    oracle_undo_wait='请等待当前动画或读档完成后再撤销。',
    oracle_undo_unavailable='当前状态或版本暂不支持撤销。',
    oracle_undo_error='撤销发生错误，历史文件已保留，请查看日志。',
    oracle_undo_write='无法写入撤销历史，原版存档保留。',
    oracle_undo_corrupt='历史节点校验失败，未执行恢复。',
    oracle_undo_profile='撤销历史不属于当前存档档位。',
    oracle_undo_experimental='实验性 · 当前牌局历史，从安装后开始记录。',
    oracle_event_depth='概率事件预测深度',
    oracle_event_condition='实验性：当前底注内连续进行同类有效判定。',
    oracle_event_wheel_condition='实验性：假设每次有一张命运之轮，保留此前版本变化。',
    oracle_event_other_actions='不含中途行动、其他同序列判定及卡牌获取过程。',
    oracle_event_no_target='已停止：没有可添加版本的小丑。',
    oracle_event_destroy_boundary='已到达销毁判定，停止继续推演此对象。',
    oracle_quick_conditional='实验性 · 现在使用／打开的结果',
    oracle_quick_more='更多结果请打开预知：',
    oracle_quick_stack='当前牌序，至下次洗牌为止。',
    oracle_quick_shop_use='按当前状态模拟，不含购买效果。',
    oracle_jokers_tab='小丑触发',
    oracle_joker_empty='当前没有支持的随机效果小丑、幸运牌或玻璃牌。',
    oracle_joker_nonrandom='幸运猫和一路狂飙本身没有独立随机抽签。',
    oracle_joker_conditional='Experimental · 当前状态下的下一次合格触发',
    oracle_joker_order_hint='先前判定、重复触发及复制效果可能改变本结果。',
    oracle_joker_current_target='当前目标',
    oracle_export_logs='导出日志 (F10)',
    oracle_export_hint='按 F10 导出诊断日志',
    oracle_export_success='诊断日志已导出',
    oracle_export_share='请将该文件发给开发者排查。',
    oracle_report_folder='打开日志文件夹',
    oracle_export_failed='诊断日志导出失败',
    oracle_export_failed_hint='请检查游戏存档目录的写入权限。',
    oracle_pack_custom_soul='自定义灵魂生成规则尚不支持预测。',
    oracle_joker_next_target='下次目标',
    oracle_joker_no_room='没有剩余栏位，本次不生成牌。',
    oracle_joker_no_target='没有合格目标，不进行随机选择。',
    oracle_joker_not_ready='出售复制尚未就绪，或没有可用栏位。',
    oracle_joker_debuffed='该牌当前已被削弱。',
    oracle_joker_mult='倍率', oracle_joker_money='金钱', oracle_joker_destroy='销毁',
    oracle_reset_ante='目标重置底注',
    oracle_trigger_j_space='下一次出牌计分前的牌型升级判定。',
    oracle_trigger_j_gros_michel='下一次回合结束的消失判定。',
    oracle_trigger_j_cavendish='下一次回合结束的消失判定。',
    oracle_trigger_j_bloodstone='下一张参与计分的红桃牌判定。',
    oracle_trigger_j_business='下一张参与计分的人头牌判定。',
    oracle_trigger_j_reserved_parking='下一张留在手中且未削弱的人头牌判定。',
    oracle_trigger_j_8_ball='有消耗牌栏位时，下一张计分的 8 的判定。',
    oracle_trigger_j_hallucination='有消耗牌栏位时，下一次开包判定。',
    oracle_trigger_m_glass='该牌计分后的下一次碎裂判定。',
    oracle_trigger_m_lucky='下一次计分触发；倍率和金钱可以同时成功。',
    oracle_trigger_j_idol='假设牌组不变，下一次目标重置。',
    oracle_trigger_j_mail='假设牌组不变，下一次目标点数重置。',
    oracle_trigger_j_ancient='下一次花色重置；排除当前目标花色。',
    oracle_trigger_j_castle='下一次花色重置；按实际牌组抽选。',
    oracle_trigger_j_misprint='下一次主计分阶段的随机倍率。',
    oracle_trigger_j_todo_list='下一次回合结束；可见牌型中排除当前目标。',
    oracle_trigger_j_invisible='现在出售已就绪的小丑；复制时去除负片。',
    oracle_trigger_j_perkeo='保留当前消耗牌，下一次离开商店。',
    oracle_trigger_j_madness='保留当前小丑，下一次选择非 Boss 盲注。',
    oracle_trigger_j_riff_raff='下一次选择盲注；最多生成两张普通小丑。',
    oracle_trigger_j_cartomancer='有消耗牌栏位时，下一次选择盲注。',
    oracle_trigger_j_sixth_sense='首手只打出一张 6，且有消耗牌栏位。',
    oracle_trigger_j_vagabond='下一次满足其余额条件的计分触发。',
    oracle_trigger_j_superposition='下一次包含 A 的合格顺子触发。',
    oracle_trigger_j_seance='有消耗牌栏位时，下一次同花顺触发。',
    oracle_trigger_j_marble='下一次选择盲注；生成一张石头牌。',
    oracle_trigger_j_certificate='下一次首次抽手牌；显示新牌和蜡封。',
    oracle_tag_after_pack='先处理前一个补充包，之后按实际选择更新。',
    oracle_tag_no_room='小丑栏位已满：不会生成小丑。',
    oracle_tag_pack_cover='封面变体随机；不影响以上内容。',
    oracle_consumables_tab="消耗牌",
    oracle_consume_empty="持有区或已打开补充包中没有消耗牌。",
    oracle_consume_selection="请先选中合法目标牌，或留出所需栏位。",
    oracle_consume_wait="请等待当前操作结束。",
    oracle_action_unsupported="当前效果暂时无法可靠预测。",
    oracle_consume_direct="实验性 · 本次使用的直接效果",
    oracle_created="生成",
    oracle_destroyed="销毁",
    oracle_target="目标",
    oracle_after_use="使用后",
    oracle_success="成功",
    oracle_fail="失败",
    oracle_money_change="金钱变化",
    oracle_hand_size_change="手牌上限变化",
    oracle_consume_selection_hint="使用当前选牌；小丑计分与数值连锁另行模拟。",

    oracle_auto_refresh='自动刷新',oracle_show_draw_order='显示抽牌顺序',
    oracle_show_future_shops='显示未来商店',oracle_show_packs='显示补充包',oracle_show_voucher='显示优惠券',
    oracle_manual_refresh_hint='关闭自动刷新后，点击刷新或切换页面读取最新状态。',
    oracle_feature_hidden='此视图已在预知设置中关闭。',oracle_slot='位置：',
    oracle_rng_enable='在设置中开启高级信息，即可查看 RNG 状态。',
    oracle_rng_readonly='当前各 RNG 键的状态 · 只读',
    oracle_predicted='预测结果：', oracle_card_key='卡牌 key：',
    oracle_pack_wait='请在商店或已打开补充包时查看此页。',
    oracle_pack_unsupported='当前状态或自定义规则暂不支持补充包预测。',
    oracle_pack_tag_unsupported='持有尚未适配或自定义的标签，暂不预测补充包。',
    oracle_pack_branch='每个包均独立按“从当前状态第一个开启”预测。',
    oracle_soul_branch='灵魂：假设生成完本包后立即使用，不进行其他操作。',
    oracle_boss_tab = '重掷 Boss', oracle_boss_branch = '在当前底注连续重掷 Boss 的结果。',
    oracle_boss_permission = '仅作预测；实际操作仍需满足优惠券、金钱与时机条件。',
    oracle_reroll = '重掷', oracle_current_shop = '当前商店', oracle_next_shop = '下一个商店',
    oracle_boosters = '补充包', oracle_shop_branch = '假设连续重掷之间不购买、不进行其他操作。',
    oracle_shop_wait = '完成本轮出牌后，可在结算画面预测下一个商店。',
    oracle_shop_unsupported = '商店预测暂不可用：存在未支持的规则、标签或过渡状态。',
    oracle_cover_unknown = '已确定为丑角包；封面变体无法确定。',
    oracle_type_Joker = '小丑牌', oracle_type_Tarot = '塔罗牌', oracle_type_Planet = '星球牌',
    oracle_type_Spectral = '幻灵牌', oracle_type_Default = '扑克牌', oracle_type_Enhanced = '增强牌',
    oracle_type_Booster = '补充包', oracle_eternal = '永恒', oracle_perishable = '易腐',
    oracle_rental = '租用', oracle_e_foil = '闪箔', oracle_e_holo = '镭射',
    oracle_e_polychrome = '多彩', oracle_e_negative = '负片',
    oracle_title = '预知', oracle_overview = '总览', oracle_settings = '设置',
    oracle_tag_unavailable='无法可靠预测',
    oracle_tag_custom='当前扩展规则尚无隔离适配。',
    oracle_tag_unsupported='尚未支持此标签。',
    oracle_tag_queue='存在尚未适配的标签组合。',
    oracle_chain_tab='标签链', oracle_stored_doubles='已存双倍标签',
    oracle_double_pending='保留等待下一次非双倍标签；不复制自身。',
    oracle_normal_voucher='正常优惠券', oracle_chain_more='完整结果见预知 → 标签链。',
    oracle_chain_reroll='重掷', oracle_chain_immediate='跳过后立即结算',
    oracle_chain_deferred='商店结算（未来条件分支）',
    oracle_chain_no_purchase='连续重掷分支假设不购买、不使用卡牌；操作后重新预测。',
    oracle_tag_not_generated='该盲注的实际标签状态尚未生成。',
    oracle_tag_future='未来底注需到达后读取实际状态。',
    oracle_tag_nope='稀有小丑持有数量已满，标签不生成牌。',
    oracle_tag_pending='初始商店没有符合条件的牌；标签保留。',
    oracle_tag_experimental='预测：Experimental',
    oracle_tag_first_shop='跳过后的首个商店',
    oracle_tag_condition_1='假设此后候选池、持有卡牌和',
    oracle_tag_condition_2='相关随机序列不变；中途操作会改变结果。',
    oracle_seed = '种子', oracle_ante = '底注',
    oracle_current_blind = '当前盲注', oracle_upcoming_blind = '待选盲注',
    oracle_completed_blind = '已完成盲注',
    oracle_stake = '赌注', oracle_deck = '牌组', oracle_unknown = '暂无信息',
    oracle_no_run = '开始或继续一局游戏后即可查看。',
    oracle_run_loading = '正在等待本局信息。',
    oracle_readonly = '当前对局信息',
    oracle_phase1 = '此版本尚未开放未来预测。',
    oracle_refresh = '刷新', oracle_enabled = '启用预知', oracle_advanced = '高级信息',
    oracle_disabled = '预知已关闭，可在设置中启用。',
    oracle_unverified_version = '此版本尚未验证，仅提供当前对局信息。',
    oracle_dependency_missing = '预知需要 Steamodded 和 Lovely。',
    oracle_ui_unavailable = '暂时无法打开预知页面。',
    oracle_config_error = '设置保存失败。',
    oracle_version = '版本',
    oracle_phase2 = '底注分页可查看 Boss、标签和优惠券预测。',
    oracle_experimental = '实验性（Experimental）· 条件预测',
    oracle_observed = '已生成 · 当前对局',
    oracle_branch_1 = '假设不购买、不跳过、不重掷 Boss；',
    oracle_branch_2 = '持有卡牌与候选池条件保持不变。',
    oracle_small_tag = '小盲注标签', oracle_big_tag = '大盲注标签',
    oracle_boss = 'Boss 盲注', oracle_voucher = '优惠券',
    oracle_validate = '核对预测结果', oracle_depth = '预测深度',
    oracle_prediction_unavailable = '预测不可用，请检查版本或不匹配日志。',
    oracle_transition = '正在切换底注，请在兑现后重新打开。',
    oracle_pool_unsupported = '此版本尚不支持当前自定义候选池规则。',
    oracle_rng_unsupported = '需要 Windows 版 Balatro 与 LuaJIT 2.0.5。',
    oracle_resample_limit = '重采样达到上限，暂不显示结果。',
    oracle_consume_effects='使用结果',oracle_branch_deck='使用后牌组',oracle_before_use='使用前',
    oracle_branch_experimental='实验性 · 使用一次 · 按当前选牌',
    oracle_branch_boundary='仅当前待抽牌堆；未模拟出牌、弃牌或新盲注洗牌。',
    oracle_branch_pack_boundary='显示关包前状态；手牌回收是下一步边界。',
    oracle_deck_branch_unavailable='当前无法可靠构建模拟牌组。',
    oracle_deck_branch_draw_boundary='暂未模拟手牌上限增加后触发的自动抽牌。',
    oracle_draw_disabled='请在预知设置中开启抽牌顺序。',
    oracle_deck_tab = '牌堆', oracle_shop_tab = '商店', oracle_packs_tab = '补充包',
    oracle_next_cards='接下来抽取 · 当前真实牌序',
    oracle_pile_next='待抽',oracle_pile_hand='手牌',oracle_pile_discard='弃牌',oracle_pile_all='全部扑克牌',
    oracle_cards_view='卡牌',oracle_list_view='列表',oracle_empty_pile='此牌堆为空。',
    oracle_deck_unavailable='当前对局暂无可读取的牌堆。',
    oracle_deck_boundary='抽牌、牌张修改和洗牌后，重新读取真实牌序。',
    oracle_deck_reshuffle='此处为当前堆叠顺序；进入下一盲注会重新洗牌。',
    oracle_shop_slots='商店栏位',
    oracle_shop_sync='购买商品或优惠券后，自动按最新状态重新预测。',
    oracle_ante_tab = '底注', oracle_rng_tab = '随机序列',
    oracle_face_down_identity='预知 · 背面卡牌的真实名称',
    oracle_hook_target='钩子：打出已选牌后将弃掉此牌',
    oracle_hook_unavailable='当前状态无法可靠预测钩子弃牌。',
    oracle_boss_analysis_tab='Boss 影响', oracle_boss_rules='规则', oracle_boss_cards='受影响牌张', oracle_boss_hand='出牌条件',
    oracle_boss_current='实验性 · 当前 Boss · 当前状态',
    oracle_boss_scheduled='实验性 · 本底注 Boss · 假设状态保持不变',
    oracle_boss_analysis_unsupported='当前状态暂不支持 Boss 分析。', oracle_boss_no_active='当前未处于 Boss 盲注。',
    oracle_boss_chicot='奇科已使 Boss 能力失效。', oracle_boss_disabled='Boss 能力已失效。',
    oracle_boss_hand_size_delta='进入时：手牌上限变化', oracle_boss_discards_delta='进入时：弃牌次数变化', oracle_boss_hands_delta='进入时：出牌次数变化',
    oracle_boss_random_boundary='仅显示规则；此处尚未模拟随机目标。',
    oracle_boss_draw_boundary='仅显示规则；尚未模拟连续抽牌与翻面事件。',
    oracle_boss_affected='被 Boss 削弱的扑克牌', oracle_boss_no_debuff='当前快照中无扑克牌被削弱。',
    oracle_boss_card_boundary='按全牌组当前属性统计；其他 Boss 效果仍适用。',
    oracle_boss_plan_hint='假设使用上述张数打出所选牌型：',
    oracle_boss_blocked='该手牌被 Boss 禁止', oracle_boss_allowed='Boss 未限制该牌型及张数',
    oracle_boss_money='Boss 直接造成的金钱变化', oracle_boss_base='基础筹码 × 倍率',
    oracle_boss_score_boundary='仅分析 Boss 效果；不含小丑结算及最终得分。',
}}}
